#ifndef _AUTO_GRANNY_H
#define _AUTO_GRANNY_H

extern int GrannyARGB8888PixelFormat;
extern int GrannyAnimationType;
extern int GrannyArtToolInfoType;
extern int GrannyBGR555PixelFormat;
extern int GrannyBGR565PixelFormat;
extern int GrannyBGR888PixelFormat;
extern int GrannyBGRA4444PixelFormat;
extern int GrannyBGRA5551PixelFormat;
extern int GrannyBGRA8888PixelFormat;
extern int GrannyBoneBindingType;
extern int GrannyBoneType;
extern int GrannyCameraInfoType;
extern int GrannyCurveType;
extern int GrannyDefinedTypes;
extern int GrannyEmptyType;
extern int GrannyExporterInfoType;
extern int GrannyFileInfoType;
extern int GrannyGBX333VertexType;
extern int GrannyGRNFileMV;
extern int GrannyIdentityTrackMask;
extern int GrannyInt16Type;
extern int GrannyInt32Type;
extern int GrannyLightInfoType;
extern int GrannyMaterialBindingType;
extern int GrannyMaterialMapType;
extern int GrannyMaterialType;
extern int GrannyMeshType;
extern int GrannyModelMeshBindingType;
extern int GrannyModelType;
extern int GrannyMorphTargetType;
extern int GrannyNullTrackMask;
extern int GrannyP3VertexType;
extern int GrannyPN33VertexType;
extern int GrannyPNG333VertexType;
extern int GrannyPNGB3333VertexType;
extern int GrannyPNGBT33332VertexType;
extern int GrannyPNGBT33333VertexType;
extern int GrannyPNGT3332VertexType;
extern int GrannyPNT332VertexType;
extern int GrannyPNT333VertexType;
extern int GrannyPT32VertexType;
extern int GrannyPWN313VertexType;
extern int GrannyPWN323VertexType;
extern int GrannyPWN343VertexType;
extern int GrannyPWNG3133VertexType;
extern int GrannyPWNG3233VertexType;
extern int GrannyPWNG3433VertexType;
extern int GrannyPWNGB31333VertexType;
extern int GrannyPWNGB32333VertexType;
extern int GrannyPWNGB34333VertexType;
extern int GrannyPWNGBT313332VertexType;
extern int GrannyPWNGBT323332VertexType;
extern int GrannyPWNGBT343332VertexType;
extern int GrannyPWNGT31332VertexType;
extern int GrannyPWNGT32332VertexType;
extern int GrannyPWNGT34332VertexType;
extern int GrannyPWNT3132VertexType;
extern int GrannyPWNT3232VertexType;
extern int GrannyPWNT3432VertexType;
extern int GrannyPeriodicLoopType;
extern int GrannyPixelLayoutType;
extern int GrannyQuadType;
extern int GrannyRGB555PixelFormat;
extern int GrannyRGB565PixelFormat;
extern int GrannyRGB888PixelFormat;
extern int GrannyRGBA4444PixelFormat;
extern int GrannyRGBA5551PixelFormat;
extern int GrannyRGBA8888PixelFormat;
extern int GrannyReal32Type;
extern int GrannyReversedGRNFileMV;
extern int GrannySkeletonType;
extern int GrannyStringType;
extern int GrannyTextTrackEntryType;
extern int GrannyTextTrackType;
extern int GrannyTextureImageType;
extern int GrannyTextureMIPLevelType;
extern int GrannyTextureType;
extern int GrannyTrackGroupType;
extern int GrannyTransformTrackType;
extern int GrannyTransformType;
extern int GrannyTriAnnotationSetType;
extern int GrannyTriMaterialGroupType;
extern int GrannyTriTopologyType;
extern int GrannyTripleType;
extern int GrannyUInt32Type;
extern int GrannyUInt8Type;
extern int GrannyVectorTrackType;
extern int GrannyVertexAnnotationSetType;
extern int GrannyVertexDataType;
extern int GrannyVertexWeightArraysType;
extern int (__stdcall *_GrannyARGB8888SwizzleNGC) (int, int, int, int, int);
extern int (__stdcall *_GrannyAbortFile) (int);
extern int (__stdcall *_GrannyAccumulateLocalTransform) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyAccumulateModelAnimations) (int, int, int, int);
extern int (__stdcall *_GrannyAccumulateModelAnimationsLOD) (int, int, int, int, int);
extern int (__stdcall *_GrannyAcquireAnimationBinding) (int);
extern int (__stdcall *_GrannyAcquireAnimationBindingFromID) (int);
extern int (__stdcall *_GrannyAddBlendDagNodeChild) (int, int);
extern int (__stdcall *_GrannyAddBone) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyAddDynamicArrayMember) (int, int, int, int, int);
extern int (__stdcall *_GrannyAddIntegerMember) (int, int, int);
extern int (__stdcall *_GrannyAddReferenceMember) (int, int, int, int);
extern int (__stdcall *_GrannyAddScalarArrayMember) (int, int, int, int);
extern int (__stdcall *_GrannyAddScalarMember) (int, int, int);
extern int (__stdcall *_GrannyAddStringMember) (int, int, int);
extern int (__stdcall *_GrannyAddTextEntry) (int, int, int);
extern int (__stdcall *_GrannyAddToCRC32) (int, int, int);
extern int (__stdcall *_GrannyAddWeight) (int, int, int);
extern int (__stdcall *_GrannyAdjustFileFixup) (int, int, int);
extern int (__stdcall *_GrannyAlignWriter) (int);
extern int (__stdcall *_GrannyAll16SwizzleNGC) (int, int, int, int, int);
extern int (__stdcall *_GrannyAllocateBSplineSolver) (int, int);
extern int (__stdcall *_GrannyAllocateFixed) (int);
extern int (__stdcall *_GrannyAllocateLODErrorSpace) (int);
extern int (__stdcall *_GrannyAllocationsBegin) ();
extern int (__stdcall *_GrannyAllocationsEnd) ();
extern int (__stdcall *_GrannyApplyRootMotionVectorsToLocalPose) (int, int, int);
extern int (__stdcall *_GrannyApplyRootMotionVectorsToMatrix) (int, int, int, int);
extern int (__stdcall *_GrannyBeginAllocationCheck) ();
extern int (__stdcall *_GrannyBeginBestMatchS3TCTexture) (int, int);
extern int (__stdcall *_GrannyBeginBinkTexture) (int, int, int, int);
extern int (__stdcall *_GrannyBeginCRC32) (int);
extern int (__stdcall *_GrannyBeginControlledAnimation) (int, int);
extern int (__stdcall *_GrannyBeginFile) (int, int, int, int);
extern int (__stdcall *_GrannyBeginFileCompression) (int, int, int, int);
extern int (__stdcall *_GrannyBeginFileDataTreeWriting) (int, int, int, int);
extern int (__stdcall *_GrannyBeginLocalPoseAccumulation) (int, int, int);
extern int (__stdcall *_GrannyBeginMesh) (int, int, int, int, int);
extern int (__stdcall *_GrannyBeginRawTexture) (int, int, int, int);
extern int (__stdcall *_GrannyBeginS3TCTexture) (int, int, int);
extern int (__stdcall *_GrannyBeginSampledAnimation) (int, int);
extern int (__stdcall *_GrannyBeginSkeleton) (int);
extern int (__stdcall *_GrannyBeginTextTrack) (int, int);
extern int (__stdcall *_GrannyBeginTrackGroup) (int, int, int, int, int);
extern int (__stdcall *_GrannyBeginTransformTrack) (int, int);
extern int (__stdcall *_GrannyBeginVariant) (int);
extern int (__stdcall *_GrannyBeginWriterCRC) (int);
extern int (__stdcall *_GrannyBinkCompressTexture) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyBinkDecompressTexture) (int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyBlendDagFreeCompletedControlsEntireTree) (int);
extern int (__stdcall *_GrannyBlendDagNodeAnimationBlendFreeCompletedControls) (int);
extern int (__stdcall *_GrannyBuildCameraMatrices) (int);
extern int (__stdcall *_GrannyBuildCompositeTransform4x3) (int, int);
extern int (__stdcall *_GrannyBuildCompositeTransform4x4) (int, int);
extern int (__stdcall *_GrannyBuildCompositeTransform) (int, int, int);
extern int (__stdcall *_GrannyBuildInverse) (int, int);
extern int (__stdcall *_GrannyBuildMeshBinding4x4Array) (int, int, int, int, int);
extern int (__stdcall *_GrannyBuildRestWorldPose) (int, int, int, int, int);
extern int (__stdcall *_GrannyBuildSkeletonRelativeTransform) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyBuildSkeletonRelativeTransforms) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyBuildTangentSpace) (int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyBuildWorldPose) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyCalculateAnimationLODAddMeshBinding) (int, int, int, int);
extern int (__stdcall *_GrannyCalculateAnimationLODBegin) (int, int);
extern int (__stdcall *_GrannyCalculateAnimationLODCleanup) (int);
extern int (__stdcall *_GrannyCalculateAnimationLODEnd) (int);
extern int (__stdcall *_GrannyCalculateLODErrorValues) (int, int, int, int);
extern int (__stdcall *_GrannyCalculateLODErrorValuesAllBindings) (int, int, int, int);
extern int (__stdcall *_GrannyCaptureCurrentStats) (int);
extern int (__stdcall *_GrannyCheckedAllocationsEnd) (int);
extern int (__stdcall *_GrannyClearArena) (int);
extern int (__stdcall *_GrannyClearBlendDagNodeChildren) (int);
extern int (__stdcall *_GrannyClearMostSeriousMessage) ();
extern int (__stdcall *_GrannyClipAngularVelocityDOFs) (int, int);
extern int (__stdcall *_GrannyClipOrientationDOFs) (int, int);
extern int (__stdcall *_GrannyClipPositionDOFs) (int, int);
extern int (__stdcall *_GrannyClipRootMotionVectors) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyClipTransformDOFs) (int, int);
extern int (__stdcall *_GrannyColumnMatrixMultiply4x3) (int, int, int);
extern int (__stdcall *_GrannyColumnMatrixMultiply4x4) (int, int, int);
extern int (__stdcall *_GrannyCompleteControlAt) (int, int);
extern int (__stdcall *_GrannyCompressContentsOfFile) (int, int, int, int, int);
extern int (__stdcall *_GrannyComputeBasisConversion) (int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyComputePeriodicLoopLog) (int, int, int);
extern int (__stdcall *_GrannyComputePeriodicLoopVector) (int, int, int);
extern int (__stdcall *_GrannyConstructBSplineBuffers) (int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyControlIsActive) (int);
extern int (__stdcall *_GrannyControlIsComplete) (int);
extern int (__stdcall *_GrannyControlModelsBegin) (int);
extern int (__stdcall *_GrannyControlModelsEnd) (int);
extern int (__stdcall *_GrannyControlModelsNext) (int);
extern int (__stdcall *_GrannyConvertFileInfoToRaw) (int, int);
extern int (__stdcall *_GrannyConvertFileToRaw) (int, int);
extern int (__stdcall *_GrannyConvertIndices) (int, int, int, int, int);
extern int (__stdcall *_GrannyConvertPixelFormat) (int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyConvertSingleObject) (int, int, int, int);
extern int (__stdcall *_GrannyConvertTree) (int, int, int);
extern int (__stdcall *_GrannyConvertTreeInPlace) (int, int, int, int);
extern int (__stdcall *_GrannyConvertVertexLayouts) (int, int, int, int, int);
extern int (__stdcall *_GrannyCopyLODErrorValuesFromAllAnimations) (int, int);
extern int (__stdcall *_GrannyCopyLODErrorValuesFromAnimation) (int, int);
extern int (__stdcall *_GrannyCopyLODErrorValuesToAllAnimations) (int, int, int);
extern int (__stdcall *_GrannyCopyLODErrorValuesToAnimation) (int, int, int);
extern int (__stdcall *_GrannyCopyLocalPose) (int, int);
extern int (__stdcall *_GrannyCopyMeshIndices) (int, int, int);
extern int (__stdcall *_GrannyCopyMeshMorphVertices) (int, int, int, int);
extern int (__stdcall *_GrannyCopyMeshVertices) (int, int, int);
extern int (__stdcall *_GrannyCopyTextureImage) (int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyCopyTrackMask) (int);
extern int (__stdcall *_GrannyCreateBlendDagNodeAnimationBlend) (int, int);
extern int (__stdcall *_GrannyCreateBlendDagNodeCallback) (int, int);
extern int (__stdcall *_GrannyCreateBlendDagNodeCrossfade) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyCreateBlendDagNodeLocalPose) (int, int);
extern int (__stdcall *_GrannyCreateBlendDagNodeWeightedBlend) (int, int, int, int);
extern int (__stdcall *_GrannyCreateBlendDagNodeWeightedBlendChildren) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyCreateControl) (int, int);
extern int (__stdcall *_GrannyCreateMemoryFileReader) (int, int, int, int, int);
extern int (__stdcall *_GrannyCreatePlatformFileReader) (int, int, int);
extern int (__stdcall *_GrannyCurveIsUncompressed) (int);
extern int (__stdcall *_GrannyDataTypeBeginsWith) (int, int);
extern int (__stdcall *_GrannyDataTypesAreEqual) (int, int);
extern int (__stdcall *_GrannyDeallocateAllFixed) (int);
extern int (__stdcall *_GrannyDeallocateBSplineSolver) (int);
extern int (__stdcall *_GrannyDeallocateFixed) (int, int);
extern int (__stdcall *_GrannyDecodeGRNReference) (int, int);
extern int (__stdcall *_GrannyDecompressData) (int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyDecompressDataChunk) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyDeformVertices) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyDeleteFileWriter) (int);
extern int (__stdcall *_GrannyDumpStatHUD) (int);
extern int (__stdcall *_GrannyDuplicateBlendDagTree) (int, int, int, int, int);
extern int (__stdcall *_GrannyEaseControlIn) (int, int, int);
extern int (__stdcall *_GrannyEaseControlOut) (int, int);
extern int (__stdcall *_GrannyEncodeImage) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyEndAllocationCheck) (int);
extern int (__stdcall *_GrannyEndCRC32) (int);
extern int (__stdcall *_GrannyEndControlledAnimation) (int);
extern int (__stdcall *_GrannyEndFile) (int, int);
extern int (__stdcall *_GrannyEndFileCompression) (int, int);
extern int (__stdcall *_GrannyEndFileDataTreeWriting) (int);
extern int (__stdcall *_GrannyEndFileRaw) (int, int);
extern int (__stdcall *_GrannyEndFileRawToWriter) (int, int);
extern int (__stdcall *_GrannyEndFileToWriter) (int, int);
extern int (__stdcall *_GrannyEndLocalPoseAccumulation) (int, int, int, int);
extern int (__stdcall *_GrannyEndMesh) (int, int, int);
extern int (__stdcall *_GrannyEndMeshInPlace) (int, int, int, int, int);
extern int (__stdcall *_GrannyEndSampledAnimation) (int);
extern int (__stdcall *_GrannyEndSkeleton) (int, int);
extern int (__stdcall *_GrannyEndSkeletonInPlace) (int, int, int);
extern int (__stdcall *_GrannyEndTextTrack) (int);
extern int (__stdcall *_GrannyEndTexture) (int);
extern int (__stdcall *_GrannyEndTextureInPlace) (int, int);
extern int (__stdcall *_GrannyEndTrackGroup) (int);
extern int (__stdcall *_GrannyEndTrackGroupInPlace) (int, int);
extern int (__stdcall *_GrannyEndTransformTrack) (int);
extern int (__stdcall *_GrannyEndVariant) (int, int, int);
extern int (__stdcall *_GrannyEndVariantInPlace) (int, int, int, int, int);
extern int (__stdcall *_GrannyEndWriterCRC) (int);
extern int (__stdcall *_GrannyEnsureExactOneNorm) (int, int);
extern int (__stdcall *_GrannyEnsureQuaternionContinuity) (int, int);
extern int (__stdcall *_GrannyEvaluateCurveAtKnotIndex) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyEvaluateCurveAtT) (int, int, int, int, int);
extern int (__stdcall *_GrannyExtractTrackMask) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyFileCRCIsValid) (int);
extern int (__stdcall *_GrannyFilterAllMessages) (int);
extern int (__stdcall *_GrannyFilterMessage) (int, int);
extern int (__stdcall *_GrannyFindAllowedLODError) (int, int, int, int);
extern int (__stdcall *_GrannyFindBlendDagTreeDepth) (int);
extern int (__stdcall *_GrannyFindBoneByName) (int, int, int);
extern int (__stdcall *_GrannyFindBoneByNameLowercase) (int, int, int);
extern int (__stdcall *_GrannyFindCloseKnot) (int, int, int, int);
extern int (__stdcall *_GrannyFindKnot) (int, int, int);
extern int (__stdcall *_GrannyFindMatchingMember) (int, int, int);
extern int (__stdcall *_GrannyFindTrackByName) (int, int, int);
extern int (__stdcall *_GrannyFindTrackByRule) (int, int, int, int);
extern int (__stdcall *_GrannyFindTrackGroupForModel) (int, int, int);
extern int (__stdcall *_GrannyFindVectorTrackByName) (int, int, int);
extern int (__stdcall *_GrannyFindVectorTrackByRule) (int, int, int, int);
extern int (__stdcall *_GrannyFitBSplineToSamples) (int, int, int, int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyFitPeriodicLoop) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyFixupFileSection) (int, int, int);
extern int (__stdcall *_GrannyFlushAllBindingsForAnimation) (int);
extern int (__stdcall *_GrannyFlushAllUnusedAnimationBindings) ();
extern int (__stdcall *_GrannyFlushAnimationBinding) (int);
extern int (__stdcall *_GrannyFreeAllFileSections) (int);
extern int (__stdcall *_GrannyFreeBlendDagEntireTree) (int);
extern int (__stdcall *_GrannyFreeBlendDagLocalPoseCache) ();
extern int (__stdcall *_GrannyFreeBlendDagNode) (int);
extern int (__stdcall *_GrannyFreeBuilderResult) (int);
extern int (__stdcall *_GrannyFreeCompletedModelControls) (int);
extern int (__stdcall *_GrannyFreeControl) (int);
extern int (__stdcall *_GrannyFreeControlIfComplete) (int);
extern int (__stdcall *_GrannyFreeControlOnceUnused) (int);
extern int (__stdcall *_GrannyFreeFile) (int);
extern int (__stdcall *_GrannyFreeFileSection) (int, int);
extern int (__stdcall *_GrannyFreeLODErrorSpace) (int);
extern int (__stdcall *_GrannyFreeLocalPose) (int);
extern int (__stdcall *_GrannyFreeMemoryArena) (int);
extern int (__stdcall *_GrannyFreeMeshBinding) (int);
extern int (__stdcall *_GrannyFreeMeshDeformer) (int);
extern int (__stdcall *_GrannyFreeModelInstance) (int);
extern int (__stdcall *_GrannyFreeStatHUDDump) (int);
extern int (__stdcall *_GrannyFreeStats) (int);
extern int (__stdcall *_GrannyFreeStringTable) (int);
extern int (__stdcall *_GrannyFreeTrackMask) (int);
extern int (__stdcall *_GrannyFreeWorldPose) (int);
extern int (__stdcall *_GrannyGRNFixUp) (int, int, int, int);
extern int (__stdcall *_GrannyGRNMarshall) (int, int, int, int);
extern int (__stdcall *_GrannyGenerateTangentSpaceFromUVs) (int);
extern int (__stdcall *_GrannyGetAllocationInformation) (int, int);
extern int (__stdcall *_GrannyGetAllocator) (int, int);
extern int (__stdcall *_GrannyGetAnimationBindingCacheStatus) (int);
extern int (__stdcall *_GrannyGetAnimationBindingFromControlBinding) (int);
extern int (__stdcall *_GrannyGetAttachmentOffset) (int, int, int, int, int);
extern int (__stdcall *_GrannyGetBinkPixelLayout) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeAnimationBlend) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeCallbackCallback) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeCallbackUserData) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeChild) (int, int);
extern int (__stdcall *_GrannyGetBlendDagNodeChildren) (int, int, int);
extern int (__stdcall *_GrannyGetBlendDagNodeChildrenCount) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeCrossfadeTrackMask) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeLocalPose) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeParent) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeResultTrackMask) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeResultWeight) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeType) (int);
extern int (__stdcall *_GrannyGetBlendDagNodeWeightedBlendSkeleton) (int);
extern int (__stdcall *_GrannyGetBlendDagTreeMotionVectors) (int, int, int, int, int);
extern int (__stdcall *_GrannyGetCameraBack) (int, int);
extern int (__stdcall *_GrannyGetCameraDown) (int, int);
extern int (__stdcall *_GrannyGetCameraForward) (int, int);
extern int (__stdcall *_GrannyGetCameraLeft) (int, int);
extern int (__stdcall *_GrannyGetCameraLocation) (int, int);
extern int (__stdcall *_GrannyGetCameraRelativePlanarBases) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyGetCameraRight) (int, int);
extern int (__stdcall *_GrannyGetCameraUp) (int, int);
extern int (__stdcall *_GrannyGetChannelComponentCount) (int, int);
extern int (__stdcall *_GrannyGetCompressedBytesPaddingSize) (int);
extern int (__stdcall *_GrannyGetControlClampedLocalClock) (int);
extern int (__stdcall *_GrannyGetControlClock) (int);
extern int (__stdcall *_GrannyGetControlCompletionCheckFlag) (int);
extern int (__stdcall *_GrannyGetControlCompletionClock) (int);
extern int (__stdcall *_GrannyGetControlDuration) (int);
extern int (__stdcall *_GrannyGetControlDurationLeft) (int);
extern int (__stdcall *_GrannyGetControlEaseCurveMultiplier) (int);
extern int (__stdcall *_GrannyGetControlEffectiveWeight) (int);
extern int (__stdcall *_GrannyGetControlFromBinding) (int);
extern int (__stdcall *_GrannyGetControlLocalDuration) (int);
extern int (__stdcall *_GrannyGetControlLoopCount) (int);
extern int (__stdcall *_GrannyGetControlLoopIndex) (int);
extern int (__stdcall *_GrannyGetControlLoopState) (int, int, int);
extern int (__stdcall *_GrannyGetControlRawLocalClock) (int);
extern int (__stdcall *_GrannyGetControlSpeed) (int);
extern int (__stdcall *_GrannyGetControlUserDataArray) (int);
extern int (__stdcall *_GrannyGetControlWeight) (int);
extern int (__stdcall *_GrannyGetConvertedTreeSize) (int, int, int);
extern int (__stdcall *_GrannyGetCounterCount) ();
extern int (__stdcall *_GrannyGetCounterResults) (int, int);
extern int (__stdcall *_GrannyGetCounterTicksPerSecond) ();
extern int (__stdcall *_GrannyGetDataTreeFromFile) (int);
extern int (__stdcall *_GrannyGetDefaultFileReaderOpenCallback) ();
extern int (__stdcall *_GrannyGetDefinedTypeCount) ();
extern int (__stdcall *_GrannyGetFileInfo) (int);
extern int (__stdcall *_GrannyGetFileSectionOfLoadedObject) (int, int);
extern int (__stdcall *_GrannyGetFileTypeTag) (int);
extern int (__stdcall *_GrannyGetFirstBindingForAnimation) (int);
extern int (__stdcall *_GrannyGetFirstUnusedAnimationBinding) ();
extern int (__stdcall *_GrannyGetGRNSectionArray) (int);
extern int (__stdcall *_GrannyGetGlobalControlsBegin) ();
extern int (__stdcall *_GrannyGetGlobalControlsEnd) ();
extern int (__stdcall *_GrannyGetGlobalLODFadingFactor) ();
extern int (__stdcall *_GrannyGetGlobalModelInstancesBegin) ();
extern int (__stdcall *_GrannyGetGlobalModelInstancesEnd) ();
extern int (__stdcall *_GrannyGetGlobalNextControl) (int);
extern int (__stdcall *_GrannyGetGlobalNextModelInstance) (int);
extern int (__stdcall *_GrannyGetGrannyHeadBezier) (int);
extern int (__stdcall *_GrannyGetGrannyHeadBezierCount) ();
extern int (__stdcall *_GrannyGetGrannyHeadWidthOverHeight) ();
extern int (__stdcall *_GrannyGetLODErrorValue) (int, int);
extern int (__stdcall *_GrannyGetLocalPoseBoneCount) (int);
extern int (__stdcall *_GrannyGetLocalPoseFillThreshold) (int);
extern int (__stdcall *_GrannyGetLocalPoseFromControlBinding) (int);
extern int (__stdcall *_GrannyGetLocalPoseTransform) (int, int);
extern int (__stdcall *_GrannyGetLogCallback) ();
extern int (__stdcall *_GrannyGetMaterialTextureByChannelName) (int, int);
extern int (__stdcall *_GrannyGetMaterialTextureByType) (int, int);
extern int (__stdcall *_GrannyGetMaximumAnimationBindingCount) ();
extern int (__stdcall *_GrannyGetMaximumBinkImageSize) (int, int, int, int);
extern int (__stdcall *_GrannyGetMaximumKnotCountForSampleCount) (int, int);
extern int (__stdcall *_GrannyGetMemberArrayWidth) (int);
extern int (__stdcall *_GrannyGetMemberCTypeName) (int);
extern int (__stdcall *_GrannyGetMemberMarshalling) (int);
extern int (__stdcall *_GrannyGetMemberTypeName) (int);
extern int (__stdcall *_GrannyGetMemberTypeSize) (int);
extern int (__stdcall *_GrannyGetMemberUnitSize) (int);
extern int (__stdcall *_GrannyGetMeshBinding4x4ArraySize) (int, int);
extern int (__stdcall *_GrannyGetMeshBindingBoneCount) (int);
extern int (__stdcall *_GrannyGetMeshBindingFromBoneIndices) (int);
extern int (__stdcall *_GrannyGetMeshBindingFromSkeleton) (int);
extern int (__stdcall *_GrannyGetMeshBindingSourceMesh) (int);
extern int (__stdcall *_GrannyGetMeshBindingToBoneIndices) (int);
extern int (__stdcall *_GrannyGetMeshBindingToSkeleton) (int);
extern int (__stdcall *_GrannyGetMeshBytesPerIndex) (int);
extern int (__stdcall *_GrannyGetMeshIndexCount) (int);
extern int (__stdcall *_GrannyGetMeshIndices) (int);
extern int (__stdcall *_GrannyGetMeshMorphTargetCount) (int);
extern int (__stdcall *_GrannyGetMeshMorphVertexCount) (int, int);
extern int (__stdcall *_GrannyGetMeshMorphVertexType) (int, int);
extern int (__stdcall *_GrannyGetMeshMorphVertices) (int, int);
extern int (__stdcall *_GrannyGetMeshTriangleCount) (int);
extern int (__stdcall *_GrannyGetMeshTriangleGroupCount) (int);
extern int (__stdcall *_GrannyGetMeshTriangleGroups) (int);
extern int (__stdcall *_GrannyGetMeshVertexCount) (int);
extern int (__stdcall *_GrannyGetMeshVertexType) (int);
extern int (__stdcall *_GrannyGetMeshVertices) (int);
extern int (__stdcall *_GrannyGetModelInitialPlacement4x4) (int, int);
extern int (__stdcall *_GrannyGetModelInstanceFromBinding) (int);
extern int (__stdcall *_GrannyGetModelUserDataArray) (int);
extern int (__stdcall *_GrannyGetMostLikelyPhysicalAspectRatio) (int, int);
extern int (__stdcall *_GrannyGetMostSeriousMessage) ();
extern int (__stdcall *_GrannyGetMostSeriousMessageType) ();
extern int (__stdcall *_GrannyGetNextBindingForAnimation) (int, int);
extern int (__stdcall *_GrannyGetNextUnusedAnimationBinding) (int);
extern int (__stdcall *_GrannyGetObjectMarshalling) (int);
extern int (__stdcall *_GrannyGetOodle1CompressBufferPaddingSize) ();
extern int (__stdcall *_GrannyGetOodle1DecompressBufferPaddingSize) ();
extern int (__stdcall *_GrannyGetOrientationSamples) (int, int);
extern int (__stdcall *_GrannyGetOriginalVertex) (int, int);
extern int (__stdcall *_GrannyGetPickingRay) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyGetPositionSamples) (int, int);
extern int (__stdcall *_GrannyGetRawImageSize) (int, int, int, int);
extern int (__stdcall *_GrannyGetRecommendedPixelLayout) (int, int);
extern int (__stdcall *_GrannyGetResultingCoincidentVertexMap) (int);
extern int (__stdcall *_GrannyGetResultingLocalPoseSize) (int);
extern int (__stdcall *_GrannyGetResultingMeshBindingSize) (int, int, int);
extern int (__stdcall *_GrannyGetResultingSkeletonSize) (int);
extern int (__stdcall *_GrannyGetResultingTextureSize) (int);
extern int (__stdcall *_GrannyGetResultingTopologySize) (int);
extern int (__stdcall *_GrannyGetResultingTrackGroupSize) (int);
extern int (__stdcall *_GrannyGetResultingVariantObjectSize) (int);
extern int (__stdcall *_GrannyGetResultingVariantTypeSize) (int);
extern int (__stdcall *_GrannyGetResultingVertexCount) (int);
extern int (__stdcall *_GrannyGetResultingVertexDataSize) (int);
extern int (__stdcall *_GrannyGetResultingVertexToTriangleMap) (int);
extern int (__stdcall *_GrannyGetResultingVertices) (int);
extern int (__stdcall *_GrannyGetResultingWorldPoseSize) (int);
extern int (__stdcall *_GrannyGetRootMotionVectors) (int, int, int, int, int);
extern int (__stdcall *_GrannyGetS3TCImageSize) (int, int, int);
extern int (__stdcall *_GrannyGetS3TCPixelLayout) (int);
extern int (__stdcall *_GrannyGetS3TCTextureFormatName) (int);
extern int (__stdcall *_GrannyGetScaleShearSamples) (int, int);
extern int (__stdcall *_GrannyGetSecondsElapsed) (int, int);
extern int (__stdcall *_GrannyGetSingleVertex) (int, int, int, int);
extern int (__stdcall *_GrannyGetSourceModel) (int);
extern int (__stdcall *_GrannyGetSourceSkeleton) (int);
extern int (__stdcall *_GrannyGetStackUnit) (int, int);
extern int (__stdcall *_GrannyGetStackUnitCount) (int);
extern int (__stdcall *_GrannyGetStandardSectionName) (int);
extern int (__stdcall *_GrannyGetSystemSeconds) ();
extern int (__stdcall *_GrannyGetTemporaryDirectory) ();
extern int (__stdcall *_GrannyGetTextureEncodingName) (int);
extern int (__stdcall *_GrannyGetTextureTypeName) (int);
extern int (__stdcall *_GrannyGetTexturedMaterialByChannelName) (int, int);
extern int (__stdcall *_GrannyGetTotalObjectSize) (int);
extern int (__stdcall *_GrannyGetTotalTypeSize) (int);
extern int (__stdcall *_GrannyGetTrackGroupFlags) (int, int, int);
extern int (__stdcall *_GrannyGetTrackGroupInitialPlacement4x4) (int, int);
extern int (__stdcall *_GrannyGetTrackInitialTransform) (int, int);
extern int (__stdcall *_GrannyGetTrackMaskBoneWeight) (int, int);
extern int (__stdcall *_GrannyGetTrackSamplerFor) (int);
extern int (__stdcall *_GrannyGetTrackSamplerIII) ();
extern int (__stdcall *_GrannyGetTrackSamplerIIU) ();
extern int (__stdcall *_GrannyGetTrackSamplerSSS) ();
extern int (__stdcall *_GrannyGetTrackSamplerUUU) ();
extern int (__stdcall *_GrannyGetTransformDeterminant) (int);
extern int (__stdcall *_GrannyGetTypeTableCount) (int);
extern int (__stdcall *_GrannyGetTypeTableFor) (int);
extern int (__stdcall *_GrannyGetVectorDifferences) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyGetVersion) (int, int, int, int);
extern int (__stdcall *_GrannyGetVersionString) ();
extern int (__stdcall *_GrannyGetVertexBoneCount) (int);
extern int (__stdcall *_GrannyGetVertexChannelCount) (int);
extern int (__stdcall *_GrannyGetVertexComponentCount) (int);
extern int (__stdcall *_GrannyGetVertexComponentIndex) (int, int);
extern int (__stdcall *_GrannyGetVertexComponentToolName) (int, int);
extern int (__stdcall *_GrannyGetVertexDiffuseColorName) (int, int);
extern int (__stdcall *_GrannyGetVertexSpecularColorName) (int, int);
extern int (__stdcall *_GrannyGetVertexTextureCoordinatesName) (int, int);
extern int (__stdcall *_GrannyGetWorldMatrixFromLocalPose) (int, int, int, int, int);
extern int (__stdcall *_GrannyGetWorldPose4x4) (int, int);
extern int (__stdcall *_GrannyGetWorldPose4x4Array) (int);
extern int (__stdcall *_GrannyGetWorldPoseBoneCount) (int);
extern int (__stdcall *_GrannyGetWorldPoseComposite4x4) (int, int);
extern int (__stdcall *_GrannyGetWorldPoseComposite4x4Array) (int);
extern int (__stdcall *_GrannyGetWriterPosition) (int);
extern int (__stdcall *_GrannyIKUpdate2Bone) (int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyIKUpdate) (int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyInPlaceSimilarityTransform4x3) (int, int, int, int);
extern int (__stdcall *_GrannyInPlaceSimilarityTransform) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyInPlaceSimilarityTransformOrientation) (int, int, int);
extern int (__stdcall *_GrannyInPlaceSimilarityTransformPosition) (int, int, int);
extern int (__stdcall *_GrannyInPlaceSimilarityTransformScaleShear) (int, int, int);
extern int (__stdcall *_GrannyInitializeDefaultCamera) (int);
extern int (__stdcall *_GrannyInitializeFileReader) (int, int, int, int, int);
extern int (__stdcall *_GrannyInitializeFixedAllocator) (int, int);
extern int (__stdcall *_GrannyInstantiateModel) (int);
extern int (__stdcall *_GrannyInvertTrackMask) (int);
extern int (__stdcall *_GrannyInvertTriTopologyWinding) (int);
extern int (__stdcall *_GrannyIsAnimationUsed) (int);
extern int (__stdcall *_GrannyIsBlendDagLeafType) (int);
extern int (__stdcall *_GrannyIsBlendDagNodeValid) (int, int, int);
extern int (__stdcall *_GrannyIsBlendDagTreeValid) (int, int, int);
extern int (__stdcall *_GrannyIsGrannyFile) (int, int, int);
extern int (__stdcall *_GrannyIsMixedMarshalling) (int);
extern int (__stdcall *_GrannyIsSpatialVertexMember) (int);
extern int (__stdcall *_GrannyKnotsAreReducible) (int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyLinearBlendTransform) (int, int, int, int);
extern int (__stdcall *_GrannyLogging) ();
extern int (__stdcall *_GrannyMakeDefaultAnimationBindingID) (int, int, int);
extern int (__stdcall *_GrannyMakeEmptyDataTypeMember) (int, int);
extern int (__stdcall *_GrannyMakeEmptyDataTypeObject) (int, int);
extern int (__stdcall *_GrannyMakeIdentity) (int);
extern int (__stdcall *_GrannyMapString) (int, int);
extern int (__stdcall *_GrannyMarkFileFixup) (int, int, int, int);
extern int (__stdcall *_GrannyMarkFileRootObject) (int, int, int);
extern int (__stdcall *_GrannyMarkMarshallingFixup) (int, int, int, int);
extern int (__stdcall *_GrannyMatrixEqualsQuaternion3x3) (int, int);
extern int (__stdcall *_GrannyMemberHasPointers) (int);
extern int (__stdcall *_GrannyMemoryArenaPush) (int, int);
extern int (__stdcall *_GrannyMergeSingleObject) (int, int, int, int);
extern int (__stdcall *_GrannyMeshBindingIsTransferred) (int);
extern int (__stdcall *_GrannyMeshIsRigid) (int);
extern int (__stdcall *_GrannyModelControlsBegin) (int);
extern int (__stdcall *_GrannyModelControlsEnd) (int);
extern int (__stdcall *_GrannyModelControlsNext) (int);
extern int (__stdcall *_GrannyModulationCompositeLocalPose) (int, int, int, int, int);
extern int (__stdcall *_GrannyMoveCameraRelative) (int, int, int, int);
extern int (__stdcall *_GrannyMultiply) (int, int, int);
extern int (__stdcall *_GrannyNewFileWriter) (int, int);
extern int (__stdcall *_GrannyNewLocalPose) (int);
extern int (__stdcall *_GrannyNewLocalPoseInPlace) (int, int);
extern int (__stdcall *_GrannyNewMemoryArena) ();
extern int (__stdcall *_GrannyNewMeshBinding) (int, int, int);
extern int (__stdcall *_GrannyNewMeshBindingInPlace) (int, int, int, int);
extern int (__stdcall *_GrannyNewMeshDeformer) (int, int, int);
extern int (__stdcall *_GrannyNewStackUnit) (int, int);
extern int (__stdcall *_GrannyNewStringTable) ();
extern int (__stdcall *_GrannyNewTrackMask) (int, int);
extern int (__stdcall *_GrannyNewWorldPose) (int);
extern int (__stdcall *_GrannyNewWorldPoseInPlace) (int, int);
extern int (__stdcall *_GrannyNextAllocation) (int);
extern int (__stdcall *_GrannyNormalizeVertices) (int, int, int);
extern int (__stdcall *_GrannyOffsetFileLocation) (int, int, int);
extern int (__stdcall *_GrannyOneNormalizeWeights) (int, int, int);
extern int (__stdcall *_GrannyOodle1BeginSimple) (int, int);
extern int (__stdcall *_GrannyOodle1Compress) (int, int, int);
extern int (__stdcall *_GrannyOodle1Decompress) (int, int, int, int, int);
extern int (__stdcall *_GrannyOodle1End) (int, int);
extern int (__stdcall *_GrannyOodle1FreeSimple) (int);
extern int (__stdcall *_GrannyPixelLayoutHasAlpha) (int);
extern int (__stdcall *_GrannyPixelLayoutsAreEqual) (int, int);
extern int (__stdcall *_GrannyPlayControlledAnimation) (int, int, int);
extern int (__stdcall *_GrannyPlayControlledAnimationBinding) (int, int, int, int);
extern int (__stdcall *_GrannyPlayControlledPose) (int, int, int, int, int);
extern int (__stdcall *_GrannyPolarDecompose) (int, int, int, int);
extern int (__stdcall *_GrannyPopStackUnits) (int, int);
extern int (__stdcall *_GrannyPostMultiplyBy) (int, int);
extern int (__stdcall *_GrannyPreMultiplyBy) (int, int);
extern int (__stdcall *_GrannyPredictWriterAlignment) (int);
extern int (__stdcall *_GrannyPrimeBlendDagLocalPoseCache) (int, int);
extern int (__stdcall *_GrannyPushSampledFrame) (int);
extern int (__stdcall *_GrannyPushTriangle) (int);
extern int (__stdcall *_GrannyPushVectorTrack) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyPushVertex) (int);
extern int (__stdcall *_GrannyQuaternionEqualsMatrix3x3) (int, int);
extern int (__stdcall *_GrannyRayIntersectsBox) (int, int, int, int, int);
extern int (__stdcall *_GrannyRayIntersectsBoxAt) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyRayIntersectsPlaneAt) (int, int, int, int, int);
extern int (__stdcall *_GrannyRayIntersectsSphere) (int, int, int, int);
extern int (__stdcall *_GrannyRayIntersectsSphereAt) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyRayIntersectsTriangleAt) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyReadEntireFile) (int);
extern int (__stdcall *_GrannyReadEntireFileFromMemory) (int, int);
extern int (__stdcall *_GrannyReadEntireFileFromReader) (int);
extern int (__stdcall *_GrannyReadFileSection) (int, int, int);
extern int (__stdcall *_GrannyReadFileSectionInPlace) (int, int, int, int);
extern int (__stdcall *_GrannyReadPartialFileFromReader) (int);
extern int (__stdcall *_GrannyRebasePointers) (int, int, int, int);
extern int (__stdcall *_GrannyRebasePointersStringCallback) (int, int, int, int, int);
extern int (__stdcall *_GrannyRecenterAllControlClocks) (int);
extern int (__stdcall *_GrannyRecompressFile) (int, int, int, int);
extern int (__stdcall *_GrannyReleaseAnimationBinding) (int);
extern int (__stdcall *_GrannyRemapAllAnimationBindingPointers) (int, int);
extern int (__stdcall *_GrannyRemapAnimationBindingPointers) (int, int);
extern int (__stdcall *_GrannyRemapTopologyMaterials) (int, int, int);
extern int (__stdcall *_GrannyRemoveBlendDagNodeChild) (int, int);
extern int (__stdcall *_GrannyRemoveTrackInitialTransform) (int);
extern int (__stdcall *_GrannyResetCounterPeaks) ();
extern int (__stdcall *_GrannyResetCounters) ();
extern int (__stdcall *_GrannyResetLODErrorSpace) (int);
extern int (__stdcall *_GrannyResetLODErrorValues) (int);
extern int (__stdcall *_GrannyResortAllAnimationTrackGroups) (int);
extern int (__stdcall *_GrannyResortAllFileTrackGroups) (int);
extern int (__stdcall *_GrannyResortTrackGroup) (int);
extern int (__stdcall *_GrannyReverseSection) (int, int, int, int);
extern int (__stdcall *_GrannyReverseTypeArray) (int, int, int);
extern int (__stdcall *_GrannySampleBSpline0x1) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline0x2) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline0x3) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline0x4) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline0x9) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x1) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x2) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x3) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x3n) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x4) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x4n) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline1x9) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x1) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x2) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x3) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x3n) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x4) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x4n) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline2x9) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x1) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x2) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x3) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x3n) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x4) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x4n) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline3x9) (int, int, int, int);
extern int (__stdcall *_GrannySampleBSpline) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannySampleBlendDagTree) (int, int);
extern int (__stdcall *_GrannySampleBlendDagTreeLOD) (int, int, int);
extern int (__stdcall *_GrannySampleModelAnimations) (int, int, int, int);
extern int (__stdcall *_GrannySampleModelAnimationsAccelerated) (int, int, int, int, int);
extern int (__stdcall *_GrannySampleModelAnimationsAcceleratedLOD) (int, int, int, int, int, int);
extern int (__stdcall *_GrannySampleModelAnimationsLOD) (int, int, int, int, int);
extern int (__stdcall *_GrannySampleSingleModelAnimation) (int, int, int, int, int);
extern int (__stdcall *_GrannySampleSingleModelAnimationLOD) (int, int, int, int, int, int);
extern int (__stdcall *_GrannySampleTrackPOLocal) (int, int, int, int, int);
extern int (__stdcall *_GrannySampleTrackUUULocal) (int, int, int, int);
extern int (__stdcall *_GrannyScaleImage) (int, int, int, int, int, int, int, int, int);
extern int (__stdcall *_GrannySeekWriterFromCurrentPosition) (int, int);
extern int (__stdcall *_GrannySeekWriterFromEnd) (int, int);
extern int (__stdcall *_GrannySeekWriterFromStart) (int, int);
extern int (__stdcall *_GrannySerializeStack) (int, int);
extern int (__stdcall *_GrannySetAllLODErrorSpace) (int, int);
extern int (__stdcall *_GrannySetAllLODErrorValues) (int, int);
extern int (__stdcall *_GrannySetAllocator) (int, int);
extern int (__stdcall *_GrannySetBinormal) (int, int, int, int, int);
extern int (__stdcall *_GrannySetBinormalTolerance) (int, int);
extern int (__stdcall *_GrannySetBlendDagNodeAnimationBlend) (int, int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeCallback) (int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeChild) (int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeChildren) (int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeCrossfade) (int, int, int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeCrossfadeWeights) (int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeLocalPose) (int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeResultTrackMask) (int, int, int);
extern int (__stdcall *_GrannySetBlendDagNodeResultWeight) (int, int);
extern int (__stdcall *_GrannySetBlendDagNodeWeightedBlend) (int, int, int, int);
extern int (__stdcall *_GrannySetBlendDagTreeClock) (int, int);
extern int (__stdcall *_GrannySetBoneParent) (int, int, int);
extern int (__stdcall *_GrannySetCameraAspectRatios) (int, int, int, int, int, int);
extern int (__stdcall *_GrannySetChannel) (int, int, int, int);
extern int (__stdcall *_GrannySetChannelTolerance) (int, int, int);
extern int (__stdcall *_GrannySetControlActive) (int, int);
extern int (__stdcall *_GrannySetControlClock) (int, int);
extern int (__stdcall *_GrannySetControlClockOnly) (int, int);
extern int (__stdcall *_GrannySetControlCompletionCheckFlag) (int, int);
extern int (__stdcall *_GrannySetControlEaseIn) (int, int);
extern int (__stdcall *_GrannySetControlEaseInCurve) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannySetControlEaseOut) (int, int);
extern int (__stdcall *_GrannySetControlEaseOutCurve) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannySetControlForceClampedLooping) (int, int);
extern int (__stdcall *_GrannySetControlLoopCount) (int, int);
extern int (__stdcall *_GrannySetControlLoopIndex) (int, int);
extern int (__stdcall *_GrannySetControlRawLocalClock) (int, int);
extern int (__stdcall *_GrannySetControlSpeed) (int, int);
extern int (__stdcall *_GrannySetControlTargetState) (int, int, int, int, int);
extern int (__stdcall *_GrannySetControlWeight) (int, int);
extern int (__stdcall *_GrannySetDefaultFileReaderOpenCallback) (int);
extern int (__stdcall *_GrannySetFileDataTreeFlags) (int, int);
extern int (__stdcall *_GrannySetFileExtraTag) (int, int, int);
extern int (__stdcall *_GrannySetFileSectionForObject) (int, int, int);
extern int (__stdcall *_GrannySetFileSectionForObjectsOfType) (int, int, int);
extern int (__stdcall *_GrannySetFileSectionFormat) (int, int, int, int);
extern int (__stdcall *_GrannySetFileWriterStringCallback) (int, int, int);
extern int (__stdcall *_GrannySetGlobalLODFadingFactor) (int);
extern int (__stdcall *_GrannySetImageScalingFilter) (int, int, int);
extern int (__stdcall *_GrannySetLODErrorValue) (int, int, int);
extern int (__stdcall *_GrannySetLocalPoseFillThreshold) (int, int);
extern int (__stdcall *_GrannySetLogCallback) (int);
extern int (__stdcall *_GrannySetLogFileName) (int, int);
extern int (__stdcall *_GrannySetMaterial) (int, int);
extern int (__stdcall *_GrannySetMaximumAnimationBindingCount) (int);
extern int (__stdcall *_GrannySetModelClock) (int, int);
extern int (__stdcall *_GrannySetNormal) (int, int, int, int, int);
extern int (__stdcall *_GrannySetNormalTolerance) (int, int);
extern int (__stdcall *_GrannySetPosition) (int, int, int, int);
extern int (__stdcall *_GrannySetSkeletonTrackMaskChainDownwards) (int, int, int, int);
extern int (__stdcall *_GrannySetSkeletonTrackMaskChainUpwards) (int, int, int, int);
extern int (__stdcall *_GrannySetSkeletonTrackMaskFromTrackGroup) (int, int, int, int, int, int);
extern int (__stdcall *_GrannySetStockBGRASpecification) (int, int, int, int, int);
extern int (__stdcall *_GrannySetStockRGBASpecification) (int, int, int, int, int);
extern int (__stdcall *_GrannySetStockSpecification) (int, int, int);
extern int (__stdcall *_GrannySetStringComparisonCallback) (int);
extern int (__stdcall *_GrannySetTangent) (int, int, int, int, int);
extern int (__stdcall *_GrannySetTangentBinormalCross) (int, int, int, int, int);
extern int (__stdcall *_GrannySetTangentBinormalCrossTolerance) (int, int);
extern int (__stdcall *_GrannySetTangentTolerance) (int, int);
extern int (__stdcall *_GrannySetTrackGroupAccumulation) (int, int, int);
extern int (__stdcall *_GrannySetTrackGroupBasisTransform) (int, int, int, int);
extern int (__stdcall *_GrannySetTrackGroupBinding) (int, int, int);
extern int (__stdcall *_GrannySetTrackGroupFlags) (int, int, int);
extern int (__stdcall *_GrannySetTrackGroupLOD) (int, int, int, int);
extern int (__stdcall *_GrannySetTrackGroupModelMask) (int, int, int);
extern int (__stdcall *_GrannySetTrackGroupTarget) (int, int, int);
extern int (__stdcall *_GrannySetTrackGroupTrackMask) (int, int, int);
extern int (__stdcall *_GrannySetTrackMaskBoneWeight) (int, int, int);
extern int (__stdcall *_GrannySetTrackMatchRule) (int, int, int, int);
extern int (__stdcall *_GrannySetTransform) (int, int, int, int);
extern int (__stdcall *_GrannySetTransformSample) (int, int, int, int, int);
extern int (__stdcall *_GrannySetTransformTrackOrientation) (int, int, int, int, int);
extern int (__stdcall *_GrannySetTransformTrackPosition) (int, int, int, int, int);
extern int (__stdcall *_GrannySetTransformTrackScaleShear) (int, int, int, int, int);
extern int (__stdcall *_GrannySetTransformWithIdentityCheck) (int, int, int, int);
extern int (__stdcall *_GrannySetVertexChannelComponentNames) (int, int, int);
extern int (__stdcall *_GrannySetVertexColor) (int, int, int, int);
extern int (__stdcall *_GrannySetVertexIndex) (int, int, int);
extern int (__stdcall *_GrannySetVertexNormal) (int, int, int);
extern int (__stdcall *_GrannySetVertexPosition) (int, int, int);
extern int (__stdcall *_GrannySetVertexUVW) (int, int, int, int);
extern int (__stdcall *_GrannySimilarityTransform) (int, int, int, int);
extern int (__stdcall *_GrannySimilarityTransformCurve3) (int, int, int, int, int);
extern int (__stdcall *_GrannySimilarityTransformCurve3x3) (int, int, int, int, int);
extern int (__stdcall *_GrannySimilarityTransformCurve4) (int, int, int, int, int);
extern int (__stdcall *_GrannySimilarityTransformTrackGroup) (int, int, int, int);
extern int (__stdcall *_GrannySleepForSeconds) (int);
extern int (__stdcall *_GrannyStackCleanUp) (int);
extern int (__stdcall *_GrannyStackInitialize) (int, int, int);
extern int (__stdcall *_GrannyStepPeriodicLoop) (int, int, int, int);
extern int (__stdcall *_GrannyStringDifference) (int, int);
extern int (__stdcall *_GrannySwapRGBAToBGRA) (int);
extern int (__stdcall *_GrannyTextureHasAlpha) (int);
extern int (__stdcall *_GrannyTransformAnimation) (int, int, int, int, int);
extern int (__stdcall *_GrannyTransformBoundingBox) (int, int, int, int);
extern int (__stdcall *_GrannyTransformCurve3) (int, int, int);
extern int (__stdcall *_GrannyTransformCurve3x3) (int, int, int);
extern int (__stdcall *_GrannyTransformCurve4) (int, int, int);
extern int (__stdcall *_GrannyTransformFile) (int, int, int, int, int);
extern int (__stdcall *_GrannyTransformMesh) (int, int, int, int, int);
extern int (__stdcall *_GrannyTransformModel) (int, int, int, int, int);
extern int (__stdcall *_GrannyTransformPoint) (int, int, int);
extern int (__stdcall *_GrannyTransformPointInPlace) (int, int);
extern int (__stdcall *_GrannyTransformSkeleton) (int, int, int, int, int);
extern int (__stdcall *_GrannyTransformTrackHasUncompressedCurves) (int);
extern int (__stdcall *_GrannyTransformTrackIsAnimated) (int);
extern int (__stdcall *_GrannyTransformTrackIsIdentity) (int);
extern int (__stdcall *_GrannyTransformVector) (int, int, int);
extern int (__stdcall *_GrannyTransformVectorInPlace) (int, int);
extern int (__stdcall *_GrannyTransformVectorInPlaceTransposed) (int, int);
extern int (__stdcall *_GrannyTransformVertices) (int, int, int, int, int, int, int);
extern int (__stdcall *_GrannyTypeHasPointers) (int);
extern int (__stdcall *_GrannyUncheckedSampleBSpline) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyUncheckedSampleBSplineN) (int, int, int, int, int, int);
extern int (__stdcall *_GrannyUnlinkFileReader) (int);
extern int (__stdcall *_GrannyUpdateBlendDagTreeMatrix) (int, int, int, int, int);
extern int (__stdcall *_GrannyUpdateModelMatrix) (int, int, int, int, int);
extern int (__stdcall *_GrannyUseExistingControlForAnimation) (int, int);
extern int (__stdcall *_GrannyVersionsMatch_) (int, int, int, int);
extern int (__stdcall *_GrannyWindowSpaceToWorldSpace) (int, int, int, int, int);
extern int (__stdcall *_GrannyWorldSpaceToWindowSpace) (int, int, int, int, int);
extern int (__stdcall *_GrannyWrite) (int, int, int);
extern int (__stdcall *_GrannyWriteDataTreeToFile) (int, int, int, int);
extern int (__stdcall *_GrannyWriteDataTreeToFileBuilder) (int, int);
extern int (__stdcall *_GrannyWriteFileChunk) (int, int, int, int, int);
extern int (__stdcall *_GrannyWriterIsCRCing) (int);
extern int (__stdcall *_GrannyZeroPeriodicLoop) (int);
extern int (__stdcall *_GrannyZeroTransform) (int);

void LoadStuff();

#endif
